#!/usr/bin/env bash

# Copyright 2021 Shay Gordon
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
if [ $# == 0 ]; then
  make
  exit $?
fi

self=$(basename $0)
home=$(dirname $0)
for cmd in $@
do
  shift

  # make commands
  case ${cmd} in
    make)   make       ;;
    clean)  make clean ;;
    all)    make all   ;;
    
    c|cpp|java|js|python)
      cd ${home}/src/main/${cmd}; make $@ ;;
  esac

  # skip docker commands if we're in a container
  if [ -f /.dockerenv ]; then                                     
    echo "${cmd}: already running in a docker container"
    exit 1                                      
  fi                                            

  # docker commands
  case ${cmd} in
    up)    docker compose up -d     ;;
    down)  docker compose down      ;;
    ps)    docker ps -a             ;;
    top)   docker compose top       ;;
    prune) docker system  prune -af ;;
    build) docker compose build     ;;
    nuke)
      docker compose down      &&
      docker system  prune -af &&
      docker compose build
      ;;

    alpine|fedora|ubuntu)
      if [ ! -z $@ ]; then
        docker compose exec ${cmd} $@
      else
        docker compose exec ${cmd} make
      fi
      exit $?
      ;;

    *)
      echo unknown command: \"$cmd\"
      ;;
  esac
done
